- name: Load openldap schemas
  shell: "{{ openldap_ldap_modify_root }} {{ openldap_schemadir }}/{{ item }}"
  register: schemas
  failed_when: false
  loop_control:
    pause: '{{ openldap_loop_pause }}'
  loop: "{{ openldap_schemas }}"
  tags:
    - schemas

- name: Configure ldap entires
  ldap_entry:
    dn: "{{ item.dn }}"
    objectClass: "{{ item.objectClass | default([]) }}"
    attributes: "{{ item.attributes | default({}) }}"
    xorder_discovery: "disable"
    state: "{{ item.state | default('present') }}"
  loop: "{{ openldap_entries }}"
  loop_control:
    pause: '{{ openldap_loop_pause }}'
  no_log: "{{ item.no_log | default('yes') }}"
  diff: "{{ item.diff | default(false) }}"
  tags: 
  - entries

- name: Configure ldap attributes
  ldap_attrs:
    dn: "{{ item.dn }}"
    ordered: "{{ item.ordered | default(false) }}"
    attributes: "{{ item.attributes | default({}) }}"
    state: "{{ item.state | default('exact') }}"
  no_log: "{{ item.no_log | default('yes') }}"
  diff: "{{ item.diff | default(false) }}"
  loop: "{{ openldap_attributes }}"
  loop_control:
    pause: '{{ openldap_loop_pause }}'
  tags: 
  - attributes
