- name: Install slapd
  package:
    name: '{{ slapd_package_name }}'
    state: present

- name: Add systemd override dir
  file:
    path: /etc/systemd/system/slapd.service.d
    state: directory

- name: Add system override file
  template:
    src: "{{ openldap_systemd_override_template }}"
    dest: /etc/systemd/system/slapd.service.d/override.conf
  tags: 
  - systemd

- name: Reload systemd
  systemd_service:
    daemon_reload: true
  notify: restart slapd
  tags:
  - systemd

- name: Enable slapd
  service:
    name: '{{ slapd_service_name }}'
    enabled: True
  tags:
  - config
  - openldap
