---
- include_vars: '{{ item }}'
  with_first_found:
    - files:
        - 'vars/{{ ansible_os_family }}.yml'
      skip: true
  tags: 
  - vars
  - openldap
  - always

- name: Include install
  include_tasks: install.yml

- name: datadir
  file:
    state: directory
    path: '{{ openldap_datadir }}'
    owner: '{{ openldap_user }}'
    group: '{{ openldap_group }}'
    mode: '0700'
  tags: 
  - config
  - openldap

# ssl/tls
- block:
  - name: ssl dir
    file:
      path: '{{ openldap_confdir }}/ssl'
      state: directory
      group: '{{ openldap_group }}'
      mode: '0770'
  
  - name: tls cert/key
    copy:
      src: 'openldap/{{ item }}'
      dest: '{{ openldap_confdir }}/ssl/{{ item }}'
      group: '{{ openldap_group }}'
      mode: '0640'
    with_items:
      - '{{ openldap_tls_cert }}'
      - '{{ openldap_tls_key }}'

  - name: tls ca
    copy:
      src: 'openldap/{{ item }}'
      dest: '{{ openldap_confdir }}/ssl/{{ item }}'
      group: '{{ openldap_group }}'
      mode: '0640'
    with_items:
      - '{{ openldap_tls_ca }}'
    when: openldap_tls_ca is defined
  
  when: 'openldap_tls_cert != ""'
  tags: config, ssl, openldap

- name: start slapd
  service:
    name: '{{ slapd_service_name }}'
    state: started
  tags: 
  - config 
  - openldap

- name: Include configure
  include_tasks: configure.yml
  tags: 
  - attributes
  - schemas
  - entries